png("plot4.png", width = 480, height = 480)
par(mfrow = c(2, 2))
plot(newlydata$datetime,newlydata$Global_active_power,type="l",ylab="Global Active Power",xlab="")
plot(newlydata$datetime,newlydata$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(newlydata$datetime,newlydata$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
lines(newlydata$datetime,newlydata$Sub_metering_2,col="red")
lines(newlydata$datetime,newlydata$Sub_metering_3,col="blue")
legend("topright", col=c("black", "blue", "red"),lty=1,legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(newlydata$datetime,newlydata$Global_reactive_power,type="l",xlab="daytime",ylab="Global_reactive_power")
dev.off()
