png(file="plot3.png")
par(mar=c(5,5,5,3))
plot(newlydata$datetime,newlydata$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
lines(newlydata$datetime,newlydata$Sub_metering_2,col="red")
lines(newlydata$datetime,newlydata$Sub_metering_3,col="blue")
legend("topright", col=c("black", "blue", "red"),lty=1,legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
